### ISSUE TITLE
Escape string for use in MySQL fulltext search

### ISSUE THREAD

**Issue by tuxes3** [whatwedo/SearchBundle#31]
## Is

Search for a query like `s)` returns an error response

## Should

Should work nomally. 

## Acceptance Criteria

- [ ] search is possible with all chars.

**Comment by tuxes3** [comment]
@rugbymauri are you aware of this bug, any thoughts on how to solve? Simpelst solution would be to remove the forbidden chars before performing the search: https://stackoverflow.com/questions/26507087/escape-string-for-use-in-mysql-fulltext-search

**Comment by ArnoEgli** [comment]
The same happens when you search for an e-mail address. It breaks off at the @ sign.
`An exception has been thrown during the rendering of a template ("An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 syntax error, unexpected '@', expecting $end").`
